### ISSUE TITLE
auto complete works for first argument only

### ISSUE THREAD

**Issue by neta-kedem** [fugazi-io/webclient#105]
for example if the syntax for the command is:
```
do something with (param1) and (param2)
```
then it will complete
`do some`
to
`do something with `

but it will complete
`do something with 4 `
to
`do something with `

**Comment by creativeChips** [comment]
`
test: {
                               title: "TEST",
                               returns: "ui.message",
                               parametersForm: "struct",
                               syntax: [ "do this with (p1 string) and (p2 string)" ],
                               handler: function (context: PrivilegedModuleContext, props: LoadProperties): string {
                                       return "test done.";
}
},`

**Comment by nitzantomer** [comment]
fixed here: https://github.com/fugazi-io/webclient/pull/109
