### ISSUE TITLE
Switching to a module system

### ISSUE THREAD

**Issue by mightyiam** [fugazi-io/webclient#23]
What's up with having no module system?

At least, that's what it seems to me.

**Comment by nitzantomer** [comment]
Yes, switching to a module system instead of namespacing on the global object is something we'd like to change to.
Unfortunately it's quite a big of a change so it will have to wait.

**Comment by amir-arad** [comment]
i'm on it

**Comment by nitzantomer** [comment]
fixed in PR: https://github.com/fugazi-io/webclient/pull/83
