### ISSUE TITLE
add npm start

### ISSUE THREAD

**Issue by wildeyes** [fugazi-io/webclient#24]
the following commands are needed to setup the project and run it:
```
cd webclient;
npm i;
tsc -p scripts;
tsc -p modules/scripts;
python -m SimpleHTTPServer #or anything else to serve static files
```

**Comment by nitzantomer** [comment]
This PR: https://github.com/fugazi-io/webclient/pull/25 added both script compilations to the npm package.
There's nothing for serving the static files yet
