### ISSUE TITLE
check installation scripts

### ISSUE THREAD

**Issue by nitzantomer** [fugazi-io/webclient#81]
from the goodness squad meeting, it seems that they are problematic.

**Comment by amir-arad** [comment]
I think It's much simpler in [my branch](https://github.com/amir-arad/webclient/tree/typescript-phase-II).
I even added a clean phase at the beginning of `npm run dev` and it works nice.

**Comment by nitzantomer** [comment]
solved in this PR: https://github.com/fugazi-io/webclient/pull/83
