### ISSUE TITLE
net commands fail

### ISSUE THREAD

**Issue by nitzantomer** [fugazi-io/webclient#91]
Executing:
```fugazi
post "https://httpbin.org/post" { key1: value1 }
```

Results with the following error:

> Cannot read property 'toLowerCase' of undefined

Same for 
```fugazi
delete "https://httpbin.org/delete" { key1: value1 }
```

**Comment by creativeChips** [comment]
https://github.com/fugazi-io/webclient/commit/453a4995da3836f32561a7d57eead635f4cf40fb
